# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JsonConverterUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/JSON格式化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setStyleSheet("font: 12pt \"Consolas\";")
        self.textEdit.setTabStopWidth(40)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/open 打开文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFormat = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/json.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormat.setIcon(icon2)
        self.actionFormat.setObjectName("actionFormat")
        self.actionJava = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/java.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJava.setIcon(icon3)
        self.actionJava.setObjectName("actionJava")
        self.actionKotlin = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/kotlin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKotlin.setIcon(icon4)
        self.actionKotlin.setObjectName("actionKotlin")
        self.actionGolang = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGolang.setIcon(icon5)
        self.actionGolang.setObjectName("actionGolang")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon6)
        self.actionClear.setObjectName("actionClear")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/复制.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/粘贴.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon8)
        self.actionPaste.setObjectName("actionPaste")
        self.actionTree = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Tree-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTree.setIcon(icon9)
        self.actionTree.setObjectName("actionTree")
        self.actionCurl = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/API.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCurl.setIcon(icon10)
        self.actionCurl.setObjectName("actionCurl")
        self.actionCompare = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompare.setIcon(icon11)
        self.actionCompare.setObjectName("actionCompare")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/about_nexttec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon12)
        self.actionAbout.setObjectName("actionAbout")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFormat)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionJava)
        self.toolBar.addAction(self.actionKotlin)
        self.toolBar.addAction(self.actionGolang)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTree)
        self.toolBar.addAction(self.actionCompare)
        self.toolBar.addAction(self.actionCurl)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JsonConverter"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionFormat.setText(_translate("MainWindow", "Format"))
        self.actionJava.setText(_translate("MainWindow", "Java"))
        self.actionKotlin.setText(_translate("MainWindow", "Kotlin"))
        self.actionGolang.setText(_translate("MainWindow", "Golang"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionTree.setText(_translate("MainWindow", "Struct"))
        self.actionTree.setToolTip(_translate("MainWindow", "Struct"))
        self.actionCurl.setText(_translate("MainWindow", "Curl"))
        self.actionCompare.setText(_translate("MainWindow", "Compare"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import resource_rc
